# Site settings
name: 金榜教育--给孩子不一样的未来
email: caojian_1104@126.com
author: 金榜教育
url: https://cc2018.github.io/kb
github: https://github.com/cc2018/kb
baseurl: "/kb"
description: 语文 英语 奥数 物理 化学 【中小学文化辅导 + 绘画 + 书法】
meta_description: personal education
motto: 语文 英语 奥数 物理 化学 【中小学文化辅导 + 绘画 + 书法】

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
plugins: [jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cc2018
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: ff1da0dd6c6a814ef6ec49dd10246092

theme: jekyll-theme-architect
